apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: library-data-backend-app
  name: library-data-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-data-backend-app
  template:
    metadata:
      labels:
        app: library-data-backend-app
    spec:
      containers:
      # /!\ manually purge kiwix-serve cache on kiwix-serve version upgrade
      # curl -X PURGE -H "X-Purge-Type: kiwix-serve" http://library-frontend-service
      # also check that varnish hack still necessary (gzip, endpoints)
      # /!\ manually trigger update-kiwixserve-template Job on kiwix-serve upgrade
      # after having updated the LIBKIWIX_VERSION field in env (and tested!)
      - image: ghcr.io/kiwix/kiwix-tools:3.7.0-1
        imagePullPolicy: IfNotPresent
        name: kiwix-tools
        args: ["kiwix-serve", "-b", "--library", "--monitorLibrary", "--threads", "16", "--searchLimit", "5", "--nodatealias", "--customIndex", "/data/kiwix-serve-templates/index-template.html", "/data/library/internal_library.xml"]
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /catalog/search?count=1
            port: 80
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 25
        volumeMounts:
        - mountPath: "/data/download/zim"
          subPath: zim
          name: download-volume
          readOnly: true
        - mountPath: "/data/library"
          name: library-volume
          readOnly: true
        - mountPath: "/data/kiwix-serve-templates"
          subPath: kiwix-serve-templates
          name: library-volume
          readOnly: true
        resources:
          requests:
            memory: "2Gi"
            cpu: "50m"
      volumes:
      - name: download-volume
        persistentVolumeClaim:
          claimName: kiwix-download-pvc
      - name: library-volume
        persistentVolumeClaim:
          claimName: kiwix-library-pvc
      nodeSelector:
        k8s.kiwix.org/role: "storage"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: library-data-backend-service
  labels:
    app: library-data-backend-app
spec:
  selector:
    app: library-data-backend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: library-catalog-backend-app
  name: library-catalog-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-catalog-backend-app
  template:
    metadata:
      labels:
        app: library-catalog-backend-app
    spec:
      containers:
        # /!\ manually purge kiwix-serve cache on kiwix-serve version upgrade
      - image: ghcr.io/kiwix/kiwix-tools:3.7.0-1
        imagePullPolicy: IfNotPresent
        name: kiwix-tools
        args: ["kiwix-serve", "--library", "--monitorLibrary", "--threads", "16", "--searchLimit", "5", "--nodatealias", "/data/library/internal_library.xml"]
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /catalog/search?count=1
            port: 80
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 20
          periodSeconds: 5
        volumeMounts:
        # https://github.com/kiwix/libkiwix/issues/754
        - mountPath: "/data/download/zim"
          subPath: zim
          name: download-volume
          readOnly: true
        - mountPath: "/data/library"
          name: library-volume
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "50m"
      volumes:
      # https://github.com/kiwix/libkiwix/issues/754
      - name: download-volume
        persistentVolumeClaim:
          claimName: kiwix-download-pvc
      - name: library-volume
        persistentVolumeClaim:
          claimName: kiwix-library-pvc
      nodeSelector:
        k8s.kiwix.org/role: "storage"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: library-catalog-backend-service
  labels:
    app: library-catalog-backend-app
spec:
  selector:
    app: library-catalog-backend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
