apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opds-redirect-ingress
  namespace: zim
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      # CORS
      add_header Access-Control-Allow-Origin "*" always;
      add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
      add_header Access-Control-Allow-Headers "Content-Type, Authorization, User-Agent" always;
      add_header Access-Control-Allow-Credentials "true" always;

      # Frame ancestors for both sites
      add_header Content-Security-Policy "frame-ancestors 'self' https://browser-extension.kiwix.org https://pwa.kiwix.org" always;

      # Handle preflight requests
      if ($request_method = 'OPTIONS') {
          return 204;
      }

      set $shouldRedirect 1;
      if ($uri ~* "/.well-known/acme-challenge/(.+)") {
        set $shouldRedirect 0;
      }
      if ($uri ~* "^/catalog/" ){
        rewrite ^/(.*) https://library.kiwix.org/$1 permanent;
        return 301 "https://library.kiwix.org/";
      }
      if ( $shouldRedirect = 1 ) {
        rewrite ^/(.*) https://library.kiwix.org/catalog/$1 permanent;
        return 301 "https://library.kiwix.org/catalog/";
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - opds.library.kiwix.org
      secretName: opds-library-kiwix-org-tls
  rules:
  - host: opds.library.kiwix.org
