apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opds-library-kiwix-org
  namespace: zim
spec:
  secretName: opds-library-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: opds.library.kiwix.org
  dnsNames:
  - opds.library.kiwix.org
