apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: browse-library-kiwix-org
  namespace: zim
spec:
  secretName: browse-library-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: browse.library.kiwix.org
  dnsNames:
  - browse.library.kiwix.org
