apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirrors-qa-api-db-pvc
  namespace: mirrors-qa
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: mirrors-qa-api-db-local-pv
