apiVersion: v1
kind: PersistentVolume
metadata:
  name: kathrin-seeder-files-local-pv
spec:
  capacity:
    storage: 5Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/seeder/files
  claimRef:
    name: seeder-files-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - seeder
