apiVersion: v1
kind: PersistentVolume
metadata:
  name: seeder-content-bundles-local-pv
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/content-bundles
  claimRef:
    name: seeder-content-bundles-pvc
    namespace: cardshop
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - seeder
