apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bt-tracker-pvc
  namespace: bittorrent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: bt-tracker-local-pv
