apiVersion: v1
kind: PersistentVolume
metadata:
  name: bt-tracker-local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/bt-tracker
  claimRef:
    name: bt-tracker-pvc
    namespace: bittorrent
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - services
