apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bittorrent
  labels:
    app: tracker-app
  name: tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker-app
  template:
    metadata:
      labels:
        app: tracker-app
    spec:
      containers:
      - image: ghcr.io/kiwix/bittorrent-tracker:latest
        imagePullPolicy: Always
        name: opentracker
        resources:
          requests:
            memory: "5Mi"
            cpu: "5m"
        ports:
          # we specifically want port 6969
        - containerPort: 6969
          hostPort: 6969
          protocol: TCP
        - containerPort: 6969
          hostPort: 6969
          protocol: UDP
      nodeSelector:
        k8s.kiwix.org/role: "services"
