apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pwa
  labels:
    app: pwa-app
  name: pwa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwa-app
  template:
    metadata:
      labels:
        app: pwa-app
    spec:
      containers:
      - image: ghcr.io/kiwix/kiwix-pwa:latest
        imagePullPolicy: Always
        name: pwa
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "8Mi"
            cpu: "1m"
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: pwa
  name: pwa-service
  labels:
    app: pwa-app
spec:
  selector:
    app: pwa-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pwa-ingress
  namespace: pwa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - pwa.kiwix.org
      secretName: pwa-kiwix-org-tls
  rules:
  - host: pwa.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pwa-service
            port:
              number: 80
