apiVersion: v1
kind: PersistentVolume
metadata:
  name: srv-s-mirrorbrain-db-local-pv
spec:
  capacity:
    # content is ~20GB ATM (Apr 2026)
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/mirrorbrain-db
  claimRef:
    name: dlsvc-mirrorbrain-db-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - dlservices
