apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zimit
  labels:
    app: api-app
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - image: ghcr.io/openzim/zimfarm-dispatcher:latest
        imagePullPolicy: Always
        name: api
        envFrom:
        - configMapRef:
            name: api-configs
        - secretRef:
            name: api-secrets
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zimit
  name: api-service
  labels:
    app: api-app
spec:
  selector:
    app: api-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: zimit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  tls:
    - hosts:
      - api.farm.zimit.kiwix.org
      secretName: api-farm-zimit-kiwix-org-tls
  rules:
  - host: api.farm.zimit.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
