apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: token-webhook-login-staging-kiwix-org
  namespace: login
spec:
  secretName: token-webhook-login-staging-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: token-webhook.login-staging.kiwix.org
  dnsNames:
  - token-webhook.login-staging.kiwix.org
