apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stats-matomo-maria-db-pvc
  namespace: stats
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: "local-storage"
  volumeName: srv-stats-matomo-maria-db-local-pv
