apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: services-ui-media-pvc
  namespace: cardshop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  volumeName: srv-services-cardshop-ui-media-local-pv
