apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: services-ui-db-pvc
  namespace: cardshop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: srv-services-cardshop-ui-db-local-pv
