---
apiVersion: batch/v1
kind: Job
metadata:
  name: borg-accessor
  namespace: zimfarm
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: borg-app
    spec:
      containers:
      - name: borg-backup
        image: ghcr.io/kiwix/borg-backup
        command: ["restore", "--name", "zimfarm-dispatcher-postgresdb", "--extract", "zimfarm-dispatcher-postgresdb__backup__2023-05-19T15:57:02"]
        imagePullPolicy: Always
        env:
        - name: BW_CLIENTID
          value: "user.db1a5587-cd88-49d1-aec4-ac660100a823"
        - name: BW_CLIENTSECRET
          value: "0caYbhFUPWqFZq9teKdwPeeAdi5WlX"
        - name: BW_PASSWORD
          value: "NVdHk2tX#UVV53"
        volumeMounts:
        - name: data-volume
          mountPath: "/restore"
          readOnly: false
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: zimfarm-api-postgres-db-pvc
      restartPolicy: Never
      nodeSelector:
        k8s.kiwix.org/role: "services"
