apiVersion: v1
kind: ConfigMap
metadata:
  name: farm-ui-configs
  namespace: zimit
data:
  config.json: |
    {
      "ZIMFARM_ZIM_DOWNLOAD_URL": "https://s3.us-west-1.wasabisys.com/org-kiwix-zimit",
      "ZIMFARM_WEBAPI": "https://api.farm.zimit.kiwix.org/v2",
      "MATOMO_ENABLED": false,
      "BLOB_MAX_SIZE": 1048576,
      "OAUTH_BASE_URL": "https://ory.login.kiwix.org",
      "LOGIN_MODES": ["oauth"],
      "OAUTH_MODE": "oidc",
      "OAUTH_CLIENT_ID": "6f4aaf40-6470-4311-ad59-4f176c0a0a53",
      "OAUTH_AUDIENCE": "5149d75a-c2ae-4441-8d92-d76ab847c488"
    }

