apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zimfarm
  labels:
    app: monitoring-app
  name: monitoring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - image: ghcr.io/kiwix/netdata:latest
        imagePullPolicy: Always
        name: netdata
        envFrom:
        # ZIMFARM_USERNAME, ZIMFARM_PASSWORD
        - secretRef:
            name: monitoring-secrets
        ports:
        - name: http
          protocol: TCP
          containerPort: 19999
        volumeMounts:
        - mountPath: "/var/cache/netdata"
          subPath: var_cache_netdata
          name: data-volume
          readOnly: false
        - mountPath: "/var/lib/netdata"
          subPath: var_lib_netdata
          name: data-volume
          readOnly: false
        - name: os-release
          mountPath: /host/etc/os-release
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "10m"
        livenessProbe:
          httpGet:
            path: /api/v1/info
            port: http
          failureThreshold: 3
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/info
            port: http
          failureThreshold: 3
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 30
      terminationGracePeriodSeconds: 300
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: monitoring-db-pvc
      - name: os-release
        hostPath:
          path: /etc/os-release
      nodeSelector:
        k8s.kiwix.org/role: "stats"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zimfarm
  name: monitoring-service
  labels:
    app: monitoring-app
spec:
  type: NodePort
  selector:
    app: monitoring-app
  ports:
  - name: netdata
    protocol: TCP
    port: 30099
    targetPort: 19999
    nodePort: 30099
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: zimfarm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/server-snippet: |
      location /robots.txt {
        add_header Content-Type "text/plain";
        return 200 "User-agent: *\nDisallow: /";
      }
spec:
  tls:
    - hosts:
      - monitoring.openzim.org
      secretName: monitoring-openzim-org-tls
  rules:
  - host: monitoring.openzim.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-service
            port:
              name: netdata
