apiVersion: v1
kind: PersistentVolume
metadata:
  name: srv-m-zim-local-pv
spec:
  capacity:
    # content is ~8TB ATM (Jan 2026)
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/zim
  claimRef:
    name: master-zim-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - master
