apiVersion: v1
kind: PersistentVolume
metadata:
  name: srv-m-openzim-nightly-local-pv
spec:
  capacity:
    # content is ~100GB ATM (Jan 2026)
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/openzim/nightly
  claimRef:
    name: master-openzim-nightly-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - master
