apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cardshop
  labels:
    app: ui-db-app
  name: ui-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-db-app
  template:
    metadata:
      labels:
        app: ui-db-app
    spec:
      containers:
      - image: docker.io/library/mariadb:10.4
        imagePullPolicy: IfNotPresent
        name: mariadb
        args: ["mysqld", "--max-allowed-packet=128M", "--innodb-buffer-pool-size=512M"]
        envFrom:
        - secretRef:
            name: ui-db-secrets
        volumeMounts:
        - name: data-volume
          mountPath: "/var/lib/mysql"
          readOnly: false
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "1280Mi"
            cpu: "20m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: cardshop-ui-db-pvc
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: cardshop
  name: ui-db-service
  labels:
    app: ui-db-app
spec:
  selector:
    app: ui-db-app
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
