apiVersion: v1
kind: ConfigMap
metadata:
  name: zimit-frontend-api-configs
  namespace: zimit
data:
  ALLOWED_ORIGINS: "https://zimit.kiwix.org"
  # farm-api URLs
  INTERNAL_ZIMFARM_WEBAPI: "https://api.farm.zimit.kiwix.org/v1"
  # where to download ZIM from (for links)
  ZIM_DOWNLOAD_URL: "https://s3.us-west-1.wasabisys.com/org-kiwix-zimit"
  # user to authenticate with to farm-api
  _ZIMFARM_USERNAME: "zimit"
  # url of callback farm-api should call on task completion
  CALLBACK_BASE_URL: "https://zimit.kiwix.org/api/v1/requests/hook"
  # mail sending details
  MAILGUN_API_URL: "https://api.mailgun.net/v3/mg.zimit.kiwix.org"
  MAILGUN_FROM: "Zimit <info@zimit.kiwix.org>"
  # task configuration
  ZIMIT_SIZE_LIMIT: "4294967296"
  ZIMIT_TIME_LIMIT: "7200"
  ZIMIT_IMAGE: "openzim/zimit:2.1.2"
  TASK_MEMORY: "3840MiB"
  TASK_DISK: "4GiB"
  TASK_CPU: "1"
  TASK_WORKER: "sisyphus"
  PUBLIC_URL: "https://zimit.kiwix.org"
  PUBLIC_API_URL: "https://zimit.kiwix.org/api/v1"
  ZIMFARM_REQUESTS_TIMEOUT: 10s
  MAILGUN_REQUESTS_TIMEOUT: 10s
  CONTACT_US_URL: "https://www.kiwix.org/en/contact/"