apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zimit-kiwix-org
  namespace: zimit
spec:
  secretName: zimit-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: zimit.kiwix.org
  dnsNames:
  - zimit.kiwix.org
