apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: dev-library-app
  name: dev-library-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-library-app
  template:
    metadata:
      labels:
        app: dev-library-app
    spec:
      initContainers:
      - image: docker.io/busybox
        name: create-empty-library
        command: ["/bin/sh", "-c", 'echo -e "<library version=\"20110515\">\n</library>" > /library/catalog.xml']
        volumeMounts:
        - mountPath: "/library"
          name: catalog-volume
          readOnly: false
        resources:
          requests:
            memory: "16Mi"
            cpu: "1m"
          limits:
            memory: "16Mi"
            cpu: "1m"
      containers:
      - image: ghcr.io/kiwix/catalog-retriever:latest
        imagePullPolicy: Always
        name: catalog-retriever
        env:
          - name: SAVE_TO
            value: /library/catalog.xml
          - name: CMS_API_URL
            value: http://api-service.cms.svc.cluster.local/v1
          - name: CMS_COLLECTION_ID
            value: staging
          - name: REFRESH_EVERY_SECONDS
            value: "300"
          - name: DEBUG
            value: ""
        volumeMounts:
        - mountPath: "/library"
          name: catalog-volume
          readOnly: false
        resources:
          requests:
            memory: "128Mi"
            cpu: "20m"
          limits:
            memory: "128Mi"
            cpu: "20m"

      - image: ghcr.io/kiwix/kiwix-tools-nightly:latest
        imagePullPolicy: Always
        command: ["kiwix-serve", "-b", "--library", "--monitorLibrary", "--searchLimit", "5", "/library/catalog.xml"]
        name: kiwix-tools
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hidden-volume
          mountPath: "/data"
          readOnly: true
        - mountPath: "/library"
          name: catalog-volume
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "20m"
          limits:
            memory: "2.5Gi"
            cpu: "800m"
      volumes:
      - name: catalog-volume
        emptyDir:
          sizeLimit: 30Mi
          medium: Memory
      - name: hidden-volume
        persistentVolumeClaim:
          claimName: browser-hidden-pvc
      nodeSelector:
        k8s.kiwix.org/role: "browser"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: dev-library-service
  labels:
    app: dev-library-app
spec:
  selector:
    app: dev-library-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-library-ingress
  namespace: zim
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
        location /robots.txt {
          add_header Content-Type "text/plain";
          return 200 "User-agent: *\nDisallow: /";
        }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - dev.library.kiwix.org
      secretName: dev-library-kiwix-org-tls
  rules:
  - host: dev.library.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-library-service
            port:
              number: 80
