apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: dev-library-app
  name: dev-library-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-library-app
  template:
    metadata:
      labels:
        app: dev-library-app
    spec:
      containers:
      - image: ghcr.io/rgaudin/kiwix-tools:nightly
        imagePullPolicy: Always
        command: ["kiwix-serve", "--library", "--monitorLibrary", "--searchLimit", "5", "/library/dev_library.xml"]
        name: kiwix-tools
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hidden-volume
          mountPath: "/data"
          readOnly: true
        - mountPath: "/library/dev_library.xml"
          subPath: dev_library.xml
          name: kiwix-library
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "20m"
          limits:
            memory: "2.5Gi"
            cpu: "100m"
      volumes:
      - name: hidden-volume
        persistentVolumeClaim:
          claimName: hidden-zim-pvc
      - name: kiwix-library
        persistentVolumeClaim:
          claimName: kiwix-library-pvc
      nodeSelector:
        k8s.kiwix.org/role: "storage"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: dev-library-service
  labels:
    app: dev-library-app
spec:
  selector:
    app: dev-library-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-library-ingress
  namespace: zim
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
        location /robots.txt {
          add_header Content-Type "text/plain";
          return 200 "User-agent: *\nDisallow: /";
        }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - dev.library.kiwix.org
      secretName: dev-library-kiwix-org-tls
  rules:
  - host: dev.library.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-library-service
            port:
              number: 80
