apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-donation-kiwix-org
  namespace: donation
spec:
  secretName: api-donation-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: api.donation.kiwix.org
  dnsNames:
  - api.donation.kiwix.org
