apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cms
  labels:
    app: db-app
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - image: docker.io/library/postgres:18.1-trixie
        imagePullPolicy: IfNotPresent
        name: postgres
        envFrom:
        - secretRef:
            name: db-secrets
        volumeMounts:
        - name: data-volume
          mountPath: "/var/lib/postgresql"
          readOnly: false
        - name: init-extensions
          mountPath: /docker-entrypoint-initdb.d/init-extensions.sh
          readOnly: true
          subPath: init-extensions.sh
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "100Mi"
            cpu: "20m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: cms-db-pvc
      - name: init-extensions
        configMap:
          name: db-configs
          defaultMode: 0755
          optional: false
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: cms
  name: db-service
  labels:
    app: db-app
spec:
  selector:
    app: db-app
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
