apiVersion: v1
kind: PersistentVolume
metadata:
  name: srv-b-zim-hashes-local-pv
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/zim-hashes
  claimRef:
    name: browser-zim-hashes-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - browser
