apiVersion: v1
kind: PersistentVolume
metadata:
  name: srv-b-wp1-local-pv
spec:
  capacity:
    # content is ~80GB ATM (Apr 2026)
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/wp1
  claimRef:
    name: browser-wp1-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - browser
