apiVersion: v1
kind: PersistentVolume
metadata:
  name: srv-b-download-local-pv
spec:
  capacity:
    # content is ~9.5TB ATM (Jan 2026)
    storage: 12Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/download
  claimRef:
    name: browser-download-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - browser
