apiVersion: v1
kind: PersistentVolume
metadata:
  name: srv-b-www-maps-local-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/www-maps
  claimRef:
    name: browser-maps-pvc
    namespace: zim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - browser
