apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-drive-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: dev-drive-local-pv
