apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: dev-drive-app
  name: dev-drive-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-drive-app
  template:
    metadata:
      labels:
        app: dev-drive-app
    spec:
      containers:
      - image: ghcr.io/kiwix/nginx-webdav:latest
        imagePullPolicy: Always
        name: nginx
        env:
          - name: NAME
            value: dev-drive
          - name: USERNAME
            value: admin
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-drive-password
                key: value
                optional: false
        volumeMounts:
        - name: data-volume
          subPath: dev
          mountPath: "/data"
          readOnly: false
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "1m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: kiwix-download-pvc
      nodeSelector:
        k8s.kiwix.org/role: "storage"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: dev-drive-service
  labels:
    app: dev-drive-app
spec:
  selector:
    app: dev-drive-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-drive-ingress
  namespace: zim
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8196m
    # see offspot/drive/drive.yaml
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $destination $http_destination;
      if ($destination ~ ^https://(.*)) {
          set $destination http://$1;
          more_set_input_headers "Destination: $destination";
          #more_set_input_headers -t 'text/plain' Destination $destination;
      }

    nginx.ingress.kubernetes.io/server-snippet: |
      location /robots.txt {
        add_header Content-Type "text/plain";
        return 200 "User-agent: *\nDisallow: /";
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - dev.kiwix.org
      secretName: dev-kiwix-org-tls
  rules:
  - host: dev.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-drive-service
            port:
              name: http
