apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zammad-redis-pvc
  namespace: zammad
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
  volumeName: services-zammad-redis-local-pv
