apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wiki
  labels:
    app: kiwix-wiki-app
  name: kiwix-wiki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwix-wiki-app
  template:
    metadata:
      labels:
        app: kiwix-wiki-app
    spec:
      containers:
      - name: anubis
        image: ghcr.io/techarohq/anubis:latest
        imagePullPolicy: Always
        env:
          - name: "BIND"
            value: ":8080"
          - name: "DIFFICULTY"
            value: "4"
          - name: ED25519_PRIVATE_KEY_HEX
            valueFrom:
              secretKeyRef:
                name: anubis-key
                key: ED25519_PRIVATE_KEY_HEX
          - name: "SERVE_ROBOTS_TXT"
            value: "true"
          - name: "TARGET"
            value: "http://localhost:80"
          - name: "OG_PASSTHROUGH"
            value: "true"
          - name: "OG_EXPIRY_TIME"
            value: "24h"
          - name: "WEBMASTER_EMAIL"
            value: "abuse@kiwix.org"
        resources:
          limits:
            cpu: 750m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      - image: ghcr.io/offspot/mediawiki:1.36.1
        imagePullPolicy: Always
        name: mediawiki
        envFrom:
        - configMapRef:
            name: kiwix-wiki-configs
        - secretRef:
            name: kiwix-wiki-secrets
        volumeMounts:
        - name: data-volume
          mountPath: "/var/www/data"
          readOnly: false
        ports:
        - containerPort: 80
        - containerPort: 3306
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: kiwix-wiki-pvc
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: wiki
  name: kiwix-wiki-service
  labels:
    app: kiwix-wiki-app
spec:
  selector:
    app: kiwix-wiki-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: anubis
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiwix-wiki-ingress
  namespace: wiki
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/server-snippet: |
      location /robots.txt {
        add_header Content-Type "text/plain";
        return 200 "User-agent: *\ncrawl-delay: 10";
      }
spec:
  tls:
    - hosts:
      - wiki.kiwix.org
      secretName: wiki-kiwix-org-tls
  rules:
  - host: wiki.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kiwix-wiki-service
            port:
              name: anubis
