apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-restore-pvc
  namespace: website
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  volumeName: website-restore-local-pv
