---
apiVersion: batch/v1
kind: Job
metadata:
  name: borg-accessor
  namespace: website
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: borg-app
    spec:
      containers:
      - name: borg-backup
        image: ghcr.io/kiwix/borg-backup
        command: ["restore", "--name", "website-files", "--extract", "website-files__backup__2025-03-10T13:15:57"]
        imagePullPolicy: Always
        env:
        - name: BW_CLIENTID
          value: "user.db1a5587-cd88-49d1-aec4-ac660100a823"
        - name: BW_CLIENTSECRET
          value: "0caYbhFUPWqFZq9teKdwPeeAdi5WlX"
        - name: BW_PASSWORD
          value: "NVdHk2tX#UVV53"
        volumeMounts:
        - name: data-volume
          mountPath: "/restore"
          readOnly: false
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: website-restore-pvc
      restartPolicy: Never
      nodeSelector:
        k8s.kiwix.org/role: "services"