apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: clients-library-kiwixserve-app
  name: clients-library-kiwixserve-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clients-library-kiwixserve-app
  template:
    metadata:
      labels:
        app: clients-library-kiwixserve-app
    spec:
      containers:
      # /!\ manually purge kiwix-serve cache on kiwix-serve version upgrade
      # curl -X PURGE -H "X-Purge-Type: kiwix-serve" http://clients-library-webcache-service
      - image: ghcr.io/kiwix/kiwix-tools:3.8.0
        imagePullPolicy: IfNotPresent
        name: kiwix-tools
        args: ["kiwix-serve", "-b", "--library", "--monitorLibrary", "--threads", "16", "--searchLimit", "5", "--nodatealias", "/data/demo/demo_library.xml"]
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /catalog/search?count=1
            port: 80
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 20
          periodSeconds: 5
        volumeMounts:
        - mountPath: "/data/zim"
          subPath: zim
          name: download-volume
          readOnly: true
        - name: hidden-volume
          mountPath: "/data/hidden-zim"
          readOnly: true
        - mountPath: "/data/demo/demo_library.xml"
          subPath: demo/demo_library.xml
          name: library-volume
          readOnly: true
        resources:
          requests:
            memory: "16Mi"
            cpu: "1m"
      volumes:
      - name: download-volume
        persistentVolumeClaim:
          claimName: kiwix-download-pvc
      - name: hidden-volume
        persistentVolumeClaim:
          claimName: hidden-zim-pvc
      - name: library-volume
        persistentVolumeClaim:
          claimName: kiwix-library-pvc
      nodeSelector:
        k8s.kiwix.org/role: "storage"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: clients-library-kiwixserve-service
  labels:
    app: clients-library-kiwixserve-app
spec:
  selector:
    app: clients-library-kiwixserve-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
