apiVersion: v1
kind: ConfigMap
metadata:
  name: clients-library-staticserver-configs
  namespace: zim
data:
  Caddyfile: |
    {
        auto_https off
    }
    :80 {
        redir / /home/

        handle_path /home/* {
          root * /var/www/html
          file_server
        }

        root * /var/www/html
        file_server

        handle_errors {
            rewrite * /dead.html
            file_server
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: clients-library-staticserver-app
  name: clients-library-staticserver-deployment
spec:
  selector:
    matchLabels:
      app: clients-library-staticserver-app
  template:
    metadata:
      labels:
        app: clients-library-staticserver-app
    spec:
      containers:
      - image: caddy:2.8.4-alpine
        imagePullPolicy: IfNotPresent
        name: caddy
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/etc/caddy/Caddyfile"
          subPath: Caddyfile
          name: configs
          readOnly: true
        - mountPath: "/var/www/html"
          subPath: demo
          name: library-volume
          readOnly: true
        resources:
          requests:
            memory: "16Mi"
            cpu: "1m"
      volumes:
      - name: library-volume
        persistentVolumeClaim:
          claimName: kiwix-library-pvc
      - name: configs
        configMap:
          name: clients-library-staticserver-configs
          defaultMode: 0755
      nodeSelector:
        k8s.kiwix.org/role: "storage"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: clients-library-staticserver-service
  labels:
    app: clients-library-staticserver-app
spec:
  selector:
    app: clients-library-staticserver-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
