cluster:
  name: kiwix-prod

destinations: # nota: this is in fact overriden in grafana.values.secret.yaml
  metricsService:
    type: prometheus
    url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    auth:
      type: basic
      username: "1172000"
  logsService:
    type: loki
    url: https://logs-prod-012.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "685075"

collectorCommon: # nota: this is in fact overriden in grafana.values.secret.yaml
  alloy:
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-011.grafana.net
      auth:
        type: basic
        username: "732042"

collectors:
  alloy:
    presets:
      [
        small,
        host-storage,
        host-cgroup,
        clustered,
        service-discovery,
        filesystem-log-reader,
        singleton,
      ]
  alloy-logs:
    presets: [small, filesystem-log-reader, daemonset]

clusterMetrics:
  enabled: true
  collector: alloy
  kube-state-metrics:
    enabled: true
    metricsTuning:
      useDefaultAllowList: true
      useIntegrationAllowList: false
  kubelet:
    enabled: true
  cadvisor:
    enabled: true

alloy:
  enabled: false

clusterEvents:
  enabled: false
  collector: alloy

podLogsViaLoki:
  enabled: true
  collector: alloy-logs
  excludeNamespaces: [ingress-nginx]

alloy-logs:
  enabled: false

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true

hostMetrics:
  enabled: true
  collector: alloy
  linuxHosts:
    enabled: true
    metricsTuning:
      useDefaultAllowList: true
      useIntegrationAllowList: false
      includeMetrics:
        - node_md_.*
