cluster:
  name: kiwix-prod

destinations: # nota: this is in fact overriden in grafana.values.secret.yaml
  metricsService:
    type: prometheus
    url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    auth:
      type: basic
      username: '1172000'
  logsService:
    type: loki
    url: https://logs-prod-012.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: '685075'

collectors:
  alloy-metrics:
    presets: [medium, clustered, statefulset]
  alloy-singleton:
    enabled: false
    presets: [small, deployment]
  alloy-logs:
    presets: [small, filesystem-log-reader, daemonset]
    liveDebugging:
      enabled: true

clusterMetrics:
  enabled: true
  collector: alloy-metrics
  kube-state-metrics:
    enabled: true
    metricsTuning:
      # No filtering, keep all metrics
      useDefaultAllowList: false
      includeMetrics:
        - alloy_build_info
  kubelet:
    enabled: true
  cadvisor:
    enabled: true

costMetrics:
  enabled: true
  collector: alloy-metrics

alloy-metrics:
  enabled: true

clusterEvents:
  enabled: true
  collector: alloy-metrics

alloy-singleton:
  enabled: true

# podLogs:
#   enabled: true
#   excludeNamespaces: [ingress-nginx]
#   # see https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-pod-logs/templates/_common_pod_discovery.alloy.tpl

podLogsViaLoki:
  enabled: true
  collector: alloy-logs
  excludeNamespaces: [ingress-nginx]

alloy-logs:
  enabled: true

annotationAutodiscovery:
  enabled: true
  collector: alloy-metrics

prometheusOperatorObjects:
  enabled: true
  collector: alloy-metrics
  crds:
    deploy: true
  podMonitors:
    enabled: true
  serviceMonitors:
    enabled: true

telemetryServices:
  kube-state-metrics:
    deploy: true
    image:
      tag: v2.19.1
    collectors:
      # - certificatesigningrequests
      # - configmaps
      # - cronjobs
      # - daemonsets
      # - deployments
      # - endpoints
      # - horizontalpodautoscalers
      # - ingresses
      - jobs
      # - leases
      # - limitranges
      # - mutatingwebhookconfigurations
      # - namespaces
      # - networkpolicies
      - nodes
      # - persistentvolumeclaims
      # - persistentvolumes
      # - poddisruptionbudgets
      - pods
      # - replicasets
      # - replicationcontrollers
      # - resourcequotas
      # - secrets
      # - services
      # - statefulsets
      # - storageclasses
      # - validatingwebhookconfigurations
      # - volumeattachments
      # - ingressclasses
      # - clusterrolebindings
      # - clusterroles
      # - roles
  node-exporter:
    deploy: true
    extraArgs:
      - '--collector.mdadm'
      - '--no-collector.netdev'
      - '--no-collector.netclass'
      - '--no-collector.softnet'
  opencost:
    deploy: true
    opencost:
      exporter:
        defaultClusterId: kiwix-prod
      prometheus:
        external:
          url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom
        existingSecretName: metricsservice-grafana-k8s-monitoring
    metricsSource: metricsService

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
    metricsTuning:
      includeMetrics:
        - node_md_.*
