cluster:
  name: kiwix-prod

destinations: # nota: this is in fact overriden in grafana.values.secret.yaml
  metricsService:
    type: prometheus
    url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    auth:
      type: basic
      username: "1172000"
  logsService:
    type: loki
    url: https://logs-prod-012.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "685075"

collectorCommon: # nota: this is in fact overriden in grafana.values.secret.yaml
  alloy:
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-011.grafana.net
      auth:
        type: basic
        username: "732042"

collectors:
  alloy:
    presets:
      [
        large,
        root,
        host-network,
        host-storage,
        host-cgroup,
        clustered,
        service-discovery,
        filesystem-log-reader,
        daemonset,
        otel-receiver,
      ]
  alloy-logs:
    presets: [small, filesystem-log-reader, daemonset]

clusterMetrics:
  enabled: true
  collector: alloy
  kube-state-metrics:
    enabled: true
  kubelet:
    enabled: true
  cadvisor:
    enabled: true

costMetrics:
  enabled: true
  collector: alloy

alloy:
  enabled: true

clusterEvents:
  enabled: true
  collector: alloy

podLogsViaLoki:
  enabled: true
  collector: alloy-logs
  excludeNamespaces: [ingress-nginx]

alloy-logs:
  enabled: true

annotationAutodiscovery:
  enabled: true
  collector: alloy

prometheusOperatorObjects:
  enabled: true
  collector: alloy
  crds:
    deploy: true
  podMonitors:
    enabled: true
  serviceMonitors:
    enabled: true

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
    extraArgs:
      - "--collector.mdadm"
      - "--no-collector.netdev"
      - "--no-collector.netclass"
      - "--no-collector.softnet"
  beyla:
    deploy: true
    k8sCache:
      replicas: 1

  opencost:
    deploy: true
    opencost:
      exporter:
        defaultClusterId: kiwix-prod
      prometheus:
        external:
          url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom
        existingSecretName: metricsservice-grafana-k8s-monitoring
    metricsSource: metricsService

hostMetrics:
  enabled: true
  collector: alloy
  linuxHosts:
    enabled: true
    metricsTuning:
      includeMetrics:
        - node_md_.*
