apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-youtube-api-keys
  namespace: zimfarm
spec:
  schedule: "0 2 1 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: ghcr.io/openzim/zimfarm-dispatcher:latest
              imagePullPolicy: IfNotPresent
              name: zimfarm
              envFrom:
              - secretRef:
                  name: report-youtube-api-keys
              env:
              - name: PYTHONPATH
                value: /app
              - name: GITHUB_REPO
                value: openzim/zim-requests
              - name: GITHUB_ISSUE_ASSIGNEES
                value: RavanJAltaie,Popolechien,benoit74
              - name: GITHUB_ISSUE_LABELS
                value: task
              - name: CREATE_ISSUE
                value: "true"
              volumeMounts:
              - name: report-youtube-api-keys-config
                mountPath: /app/maint-scripts/report_youtube_api_keys.conf.json
                subPath: report_youtube_api_keys.conf.json
                readOnly: true
              workingDir: /app/maint-scripts
              command: ["/app/maint-scripts/report_youtube_api_keys.py"]
              resources:
                requests:
                  cpu: 100m
                  memory: 64Mi
          volumes:
          - name: report-youtube-api-keys-config
            configMap:
              name: report-youtube-api-keys
          nodeSelector:
            k8s.kiwix.org/role: "services"
