apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: nautilus
  labels:
    app: api-db-app
  name: api-db-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-db-app
  serviceName: api-db-service
  template:
    metadata:
      labels:
        app: api-db-app
    spec:
      containers:
      - image: docker.io/library/postgres:15.3-bullseye
        imagePullPolicy: Always
        name: postgresdb
        envFrom:
        - secretRef:
            name: api-db-secrets
        volumeMounts:
        - name: data-volume
          mountPath: "/var/lib/postgresql/data"
          readOnly: false
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "20Mi"
            cpu: "10m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: nautilus-api-db-pvc
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: nautilus
  name: api-db-service
  labels:
    app: api-db-app
spec:
  selector:
    app: api-db-app
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
