apiVersion: v1
kind: PersistentVolume
metadata:
  name: services-zammad-elasticsearch-local-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/zammad/elasticsearch
  claimRef:
    name: zammad-elasticsearch-pvc
    namespace: zammad
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - services
