apiVersion: v1
kind: ConfigMap
metadata:
  name: master-mirror-configs
  namespace: zim
data:
  vhost.conf: |
    server {
      listen 80;
      server_name _;
      access_log /var/log/nginx/access.log vhost;
      access_log /dev/stdout vhost;
      root /var/www;
      default_type application/octet-stream;
      autoindex on;
      autoindex_exact_size off;
      autoindex_localtime off;
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
      location = /README {
        types { } default_type "text/plain; charset=utf-8";
      }
    }
  README: |
    mirror.download.kiwix.org: Kiwix's own download mirror.

    /!\ This mirror's main purpose is to serve Kiwix binaries.
    It also serves ZIM files but this is intended only for other mirrors to sync.

    Please use https://lb.download.kiwix.org instead to be redirected to the
    most appropriate mirror.

    Please consider downloading via torrents as this spread the bandwidth requirements
    over all the torrent peers.
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: master-mirror-app
  name: master-mirror-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-mirror-app
  template:
    metadata:
      labels:
        app: master-mirror-app
    spec:
      containers:
      - image: docker.io/nginx:1.21
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/zim"
          name: zim-volume
          readOnly: true
        - mountPath: "/var/www/release"
          name: kiwix-release-volume
          readOnly: true
        - mountPath: "/var/www/nightly"
          name: kiwix-nightly-volume
          readOnly: true
        - mountPath: "/var/log/nginx"
          subPath: mirror-download-kiwix
          name: nginx-logs-volume
          readOnly: false
        - name: configs
          mountPath: "/var/www/README"
          subPath: README
          readOnly: true
        - name: configs
          mountPath: "/etc/nginx/conf.d/default.conf"
          subPath: vhost.conf
          readOnly: true
        - name: nginx-configs
          mountPath: "/etc/nginx/mime.types"
          subPath: mime.types
          readOnly: true
        - name: nginx-configs
          mountPath: "/etc/nginx/conf.d/gzip.conf"
          subPath: gzip.conf
          readOnly: true
        - name: nginx-configs
          mountPath: "/etc/nginx/conf.d/01vhost-logfmt.conf"
          subPath: vhost-logfmt.conf
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
      volumes:
      - name: zim-volume
        persistentVolumeClaim:
          claimName: master-zim-pvc
      - name: kiwix-release-volume
        persistentVolumeClaim:
          claimName: master-kiwix-release-pvc
      - name: kiwix-nightly-volume
        persistentVolumeClaim:
          claimName: master-kiwix-nightly-pvc
      - name: nginx-logs-volume
        persistentVolumeClaim:
          claimName: master-www-logs-pvc
      - name: configs
        configMap:
          name: master-mirror-configs
      - name: nginx-configs
        configMap:
          name: nginx-configs
      nodeSelector:
        k8s.kiwix.org/role: "master"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: master-mirror-service
  labels:
    app: master-mirror-app
spec:
  selector:
    app: master-mirror-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: master-mirror-ingress
  namespace: zim
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
      # kiwix-js requests
      add_header Access-Control-Allow-Origin *;
      gzip on;
      gzip_types
        application/atom+xml
        application/javascript
        application/x-javascript
        application/json
        application/rss+xml
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/svg+xml
        image/x-icon
        text/css
        text/plain
        text/xml
        text/x-component;
spec:
  ingressClassName: nginx
  tls:
    # - hosts:
    #   - mirror.download.kiwix.org
    #   secretName: mirror-download-kiwix-org-tls
    - hosts:
      - mirror2.download.kiwix.org
      secretName: mirror2-download-kiwix-org-tls
    # - hosts:
    #   - master.download.kiwix.org
    #   secretName: master-download-kiwix-org-tls
  rules:
  - host: mirror2.download.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: master-mirror-service
            port:
              number: 80
  # - host: master.download.kiwix.org
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: master-mirror-service
  #           port:
  #             number: 80
