apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: login-kiwix-org
  namespace: login
spec:
  secretName: login-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: login.kiwix.org
  dnsNames:
  - login.kiwix.org
