apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: login
  labels:
    app: login-app
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
      - image: ghcr.io/kiwix/login:latest
        imagePullPolicy: Always
        name: login
        volumeMounts:
        - name: configs
          mountPath: /usr/share/caddy/assets/config.json
          readOnly: true
          subPath: config.json
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
      volumes:
      - name: configs
        configMap:
          name: login-configs
          defaultMode: 0755
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: login
  name: login-service
  labels:
    app: login-app
spec:
  selector:
    app: login-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-ingress
  namespace: login
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - login.kiwix.org
      secretName: login-kiwix-org-tls
  rules:
  - host: login.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: login-service
            port:
              number: 80
