apiVersion: batch/v1
kind: CronJob
metadata:
  name: library-generator
  namespace: zim
spec:
  schedule: "30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: debian
              image: ghcr.io/kiwix/maintenance:latest
              imagePullPolicy: Always
              env:
              - name: INSTALL_SCRIPTS
                value: "library-maint#github://kiwix/operations/zim/library-mgmt/library-maint.py"
              - name: VARNISH_URL
                value: "http://library-frontend-service"
              - name: MIRRORBRAIN_URL
                value: "http://mirrorbrain-web-service"
              - name: ZIM_DIRENTLOOKUPCACHE
                value: "1"
              - name: MIRRORBRAIN_DB_DSN
                value: "postgresql://mirrorbrain:@mirrorbrain-db-service:5432/mirrorbrain"
              volumeMounts:
              - name: kiwix-download
                subPath: library
                mountPath: "/data/download/library"
                readOnly: false
              - name: kiwix-library
                mountPath: "/data/library"
                readOnly: false
              - name: kiwix-download
                subPath: zim
                mountPath: "/data/download/zim"
                readOnly: false
              - mountPath: "/data/maps/zim.map"
                subPath: zim.map
                name: maps-volume
                readOnly: false
              args: ["library-maint", "--zim-root", "/data/download/zim", "--library-dest", "/data/download/library/library_zim.xml", "--internal-zim-root", "/data/download/zim", "--internal-library-dest", "/data/library/internal_library.xml", "--redirects-root", "/data/download", "--zim-redirects-map", "/data/maps/zim.map", "--nb-keep-zim", "2", "--nb-exposed-zim", "1", "--log-to", "/data/library/library_maint.log", "all"]
              resources:
                requests:
                  cpu: 200m
                  memory: 1Gi
          volumes:
          - name: kiwix-download
            persistentVolumeClaim:
              claimName: kiwix-download-pvc
          - name: kiwix-library
            persistentVolumeClaim:
              claimName: kiwix-library-pvc
          - name: maps-volume
            persistentVolumeClaim:
              claimName: maps-pvc
          restartPolicy: Never
          nodeSelector:
            k8s.kiwix.org/role: "storage"
