apiVersion: batch/v1
kind: Job
metadata:
  name: maintenance
  namespace: zim
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: debian
          image: ghcr.io/rgaudin/debian:dev
          imagePullPolicy: Always
          env:
          - name: VARNISH_URL
            value: "http://library-frontend-service"
          - name: MIRRORBRAIN_URL
            value: "http://mirrorbrain-web-service"
          - name: WIKI_DOMAIN
            value: "wiki.kiwix.org"
          - name: WIKI_USERNAME
            value: "Reg@library-maint"
          - name: WIKI_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wiki-credentials
                key: password
          - name: WIKI_PAGE
            value: "Template:ZIMdumps/content"
          volumeMounts:
          - name: kiwix-download
            subPath: library/library_zim.xml
            mountPath: "/data/download/library/library_zim.xml"
            readOnly: true
          - name: kiwix-download
            subPath: zim
            mountPath: "/data/download/zim"
            readOnly: false
          - name: kiwix-library
            subPath: deleted-zim
            mountPath: "/data/library/deleted-zim"
            readOnly: false
          args: ["bash", "-c", "sleep infinity"]
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
      volumes:
      - name: kiwix-download
        persistentVolumeClaim:
          claimName: kiwix-download-pvc
      - name: kiwix-library
        persistentVolumeClaim:
          claimName: kiwix-library-pvc
      restartPolicy: Never
      nodeSelector:
        k8s.kiwix.org/role: "storage"
