apiVersion: batch/v1
kind: Job
metadata:
  name: maintenance
  namespace: zim
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: debian
          image: ghcr.io/kiwix/maintenance:latest
          imagePullPolicy: Always
          env:
          - name: VARNISH_URLS
            value: "http://library-frontend-service|http://demo-library-frontend-service"
          - name: MIRRORBRAIN_URL
            value: "http://mirrorbrain-web-service"
          volumeMounts:
          - name: kiwix-download
            subPath: library/library_zim.xml
            mountPath: "/data/download/library/library_zim.xml"
            readOnly: true
          - name: kiwix-download
            subPath: zim
            mountPath: "/data/download/zim"
            readOnly: false
          - name: hidden-volume
            mountPath: "/data/hidden-zim"
            readOnly: false
          args: ["bash", "-c", "sleep infinity"]
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
      volumes:
      - name: kiwix-download
        persistentVolumeClaim:
          claimName: kiwix-download-pvc
      - name: hidden-volume
        persistentVolumeClaim:
          claimName: hidden-zim-pvc
      restartPolicy: Never
      nodeSelector:
        k8s.kiwix.org/role: "storage"
