#!/usr/bin/env python3

""" Rewrites .htaccess files on download-kiwix-org with updated descriptions """

import argparse
import pathlib
import sys

FOLDERS_MAP = {
    "archive": "Deprecated stuff kept only for historical purpose",
    "dev": "Development files (tools & dependencies), for developers",
    "library": "XML and YAML files describing all available content, for developers",
    "nightly": "Binaries and source code tarballs compiled auto. "
    "once a day, for developers",
    "other": "Misc files, mostly mirrored for third party projects",
    "release": "All versions of Kiwix software (no content)",
    "zim": "ZIM files, content packages for offline use with Kiwix readers",
}


def write_htaccess_files(download_root: pathlib.Path):
    content = "#\n# Please do not edit this file manually\n#\n"
    for folder, description in FOLDERS_MAP.items():
        content += f'AddDescription "{description}" {folder}\n'

    with open(download_root / ".htaccess", "w") as fh:
        fh.write(content)

    for folder in FOLDERS_MAP.keys():
        fpath = download_root / folder / ".htaccess"
        if not fpath.parent.is_dir():
            print(f"{fpath.parent} folder doesn't exist. Please update the script!")
            continue
        with open(fpath, "w") as fh:
            fh.write('AddDescription " " *\n')


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="write-htaccess",
        description="Rewrite descriptions .htaccess for download root and subfolders",
    )
    parser.add_argument(
        "--download-root",
        required=True,
        help="Kiwix Download root folder to write .htaccess files in.",
        dest="download_root",
    )
    args = parser.parse_args()

    sys.exit(
        write_htaccess_files(pathlib.Path(args.download_root).expanduser().resolve())
    )
