apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configs
  namespace: nautilus
data:
  NAUTILUS_WEB_API: "https://api.nautilus.openzim.org/v1"
  NAUTILUS_FILE_QUOTA: "500000000"
  NAUTILUS_PROJECT_QUOTA: "2000000000"
  NAUTILUS_FILE_REFRESH_EVERY_MS: "5000"
