apiVersion: v1
kind: ConfigMap
metadata:
  name: status-configs
  namespace: zimfarm
data:
  DEBUG: "F"
  REQUESTS_TIMEOUT: 30s
  ZIMFARM_API_URL: https://api.farm.openzim.org/v2
  ZIMFARM_FRONTEND_URL: https://farm.openzim.org
  AUTH_MODE: oauth
  ZIMFARM_OAUTH_ISSUER: https://ory.login.kiwix.org
  ZIMFARM_OAUTH_CLIENT_ID: 9e4b5284-734a-489d-a369-a42923bc36aa
  ZIMFARM_OAUTH_AUDIENCE_ID: bada4130-5143-4524-a0bb-0d69671beee2


