apiVersion: v1
kind: PersistentVolume
metadata:
  name: zimfarm-drive-local-pv
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/zimfarm-drive
  claimRef:
    name: drive-local-pvc
    namespace: zimfarm
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - services
