apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mirrors-qa-kiwix-org
  namespace: mirrors-qa
spec:
  secretName: mirrors-qa-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: mirrors-qa.kiwix.org
  dnsNames:
  - mirrors-qa.kiwix.org
