apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-restore-db-pvc
  namespace: website
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: website-restore-db-local-pv
