apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drives-files-pvc
  namespace: drives
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeName: drives-files-local-pv
