apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drive-kiwix-org
  namespace: drives
spec:
  secretName: drive-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: drive.kiwix.org
  dnsNames:
  - drive.kiwix.org
