apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drives-kiwix-org
  namespace: drives
spec:
  secretName: drives-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: drives.kiwix.org
  dnsNames:
  - drives.kiwix.org
