apiVersion: v1
kind: PersistentVolume
metadata:
  name: mirrors-qa-ui-db-local-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/mirrors-qa/ui-postgresdb
  claimRef:
    name: mirrors-qa-ui-db-pvc
    namespace: mirrors-qa
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - services
