apiVersion: v1
kind: ConfigMap
metadata:
  name: dropbox-host-pubkeys
  namespace: cardshop
# sshd host public keys, corresponding to the secret ones.
# Allows maintaining fingerprint accross sshd_reinstalls (image rebuilds)
data:
  ecdsa: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNdfdm4G1tTokY4WkZGdqCako91J8arkaxD8w+uqyt7P4HwH5NKrPOQl9MvKGvDUkm07k+qYrcMT9Y38Fs8Uegs= root@dropbox
  ed25519: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIqYT8Y03d6iwpRsr17ERiCfGMiNtRwFnr5F3Sbby6Wh root@dropbox
  rsa: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDuMXeVWf7Q3JFfXCIuMnEOdTEjtPHVto1PMJ0baC8ByOyAoG/d02sG6H1BWzneBVvzZaNOD5F1HjuJrBzDFnCvcE2SoOt9jQS3lXI9cm1PEyaovZoaYQ5yUtRgwVjAP/PFr8HUKPYJYhyP0NspVG5HxvylvgTfz+2NJe4Dc7RDAccD32ucezuqRAHkiP7b5jytAiViBASq2fVGWHbXo6rqoY2kxBbpUfb9xLy9VnbmkcQBW/Cfk2zJhQjh/uu39wWBQnY1NaQ9D38pVWStU2rfZCeuOZ8l6bwZsROVoL61IKEq/HFEaM6jPExlLWs10qBwrQqE+/t6lV0vjyeOK94AeoSmZGGw8NdEzIVaBhSvpxA8PusZjnSvbyjGxTk1WfpmVdsPk9idnvvkFp4melf4HsUneEdahTexCCDVvBW2bpVHpahojrGDc+Y0aRxs3AOFmgBagkI1VPwfZ9u1ceKW2yUjU3jBpk5NWUG1eZoqAzvLLPvjjTXOAAODgHX9uaE= root@dropbox
