# builds dropbox
# filesystem configuration
#
# GENERALS
# - rules are same for openzim and kiwix
# - each tool/product sits in its own folder with release
# - there is no subfolder per tool (only applies to some archives)
# - each of such tool folder is own by one expected uploader user
# - each of those are readable by users (gid100) group and world executable (nginx, uid101)
# - each of those folder has sticky bit and setgid
#
# - nightlies has one folder per day
# - all projects push to that single folder
# - no subfolders
# - nightly folders are own by root and group users (gid100)
#
# NOTES
# - nightly folders have to be created automatically with root:100 and chmod 3775
# otherwise the first project uploading to it would create it with improper mode/owner
# - new release project folders must be created manually and assigned to its owner
#
# RULES
#
# release and nightly top folders are owned by root:users with 645
# - can be listed by anyone both for traversal and nginx
# each nighly folder is created by root:users with 3775
# - group users can write to it and list its content
# - others can list its content (nginx)
# - setgid so new files are owned by :users as well
# - sticky bit so that only the one uploading a file can remove/rename it
# per-project release folder are own by owner user and users group with 3745
# - only owner can write
# - others can list (nginx)
# - setgid so new files are owned by :users as well
# - sticky bit so that only the owner can remove/rename it
# 
#
# cd /data/kiwix
# chmod -R 645 release
# chown root:users nightly/*
# chmod -R 645 nightly
# chmod 2655 nightly
# chmod 3775 nightly/*
# 
# chown -R 1003:users release/firefox-os
# chmod 3745 release/firefox-os
# chown -R 1003:users release/ubuntu-touch
# chmod 3745 release/ubuntu-touch
# chown -R 1003:users release/browsers/chrome
# chmod 3745 release/browsers/chrome
# chown -R 1003:users release/browsers/edge
# chmod 3745 release/browsers/edge
# chown -R 1003:users release/browsers/firefox
# chmod 3745 release/browsers/firefox
# chown -R 1002:users release/kiwix-android
# chmod 3745 release/kiwix-android
# chown -R 1004:users release/kiwix-js-windows
# chmod 3745 release/kiwix-js-windows
# chown -R 1004:users release/kiwix-js-electron
# chmod 3745 release/kiwix-js-electron
# chown -R 1007:users release/kiwix-macos
# chmod 3745 release/kiwix-macos
# chown -R 1005:users release/kiwix-desktop
# chmod 3745 release/kiwix-desktop
# chown -R 1005:users release/kiwix-tools
# chmod 3745 release/kiwix-tools
# chown -R 1005:users release/libkiwix
# chmod 3745 release/libkiwix
# 
# cd /data/openzim
# chmod -R 645 release
# chown root:users nightly/*
# chmod -R 645 nightly
# chmod 2655 nightly
# chmod 3775 nightly/*
# chown -R 1006:users release/javascript-libzim
# chmod 3745 release/javascript-libzim
# chown -R 1005:users release/libzim
# chmod 3745 release/libzim
# chown -R 1005:users release/zim-tools
# chmod 3745 release/zim-tools
# chown -R 1005:users release/zimwriterfs
# chmod 3745 release/zimwriterfs
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: builds-dropbox-app
  name: builds-dropbox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: builds-dropbox-app
  template:
    metadata:
      labels:
        app: builds-dropbox-app
    spec:
      containers:
      - image: ghcr.io/kiwix/dropbox:latest
        imagePullPolicy: Always
        name: dropbox
        env:
          - name: USERS
            valueFrom:
              configMapKeyRef:
                name: dropbox-pubkeys
                key: users
                optional: false
        volumeMounts:
        # user: kiwix-js (nightly and own releases)
        - name: kiwix-nightly-volume
          mountPath: "/jails/kiwix-js/data/kiwix/nightly"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "firefox-os"
          mountPath: "/jails/kiwix-js/data/kiwix/release/firefox-os"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "ubuntu-touch"
          mountPath: "/jails/kiwix-js/data/kiwix/release/ubuntu-touch"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "browsers/chrome"
          mountPath: "/jails/kiwix-js/data/kiwix/release/browsers/chrome"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "browsers/edge"
          mountPath: "/jails/kiwix-js/data/kiwix/release/browsers/edge"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "browsers/firefox"
          mountPath: "/jails/kiwix-js/data/kiwix/release/browsers/firefox"
          readOnly: false

        # user: kiwix-js-pwa (nightly and own releases)
        - name: kiwix-nightly-volume
          mountPath: "/jails/kiwix-js-pwa/data/kiwix/nightly"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "kiwix-js-windows"
          mountPath: "/jails/kiwix-js-pwa/data/kiwix/release/kiwix-js-windows"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "kiwix-js-electron"
          mountPath: "/jails/kiwix-js-pwa/data/kiwix/release/kiwix-js-electron"
          readOnly: false

        # user: kiwix-android (kiwix nightly)
        - name: kiwix-nightly-volume
          mountPath: "/jails/kiwix-android/data/kiwix/nightly"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "kiwix-android"
          mountPath: "/jails/kiwix-android/data/kiwix/release/kiwix-android"
          readOnly: false

        # user: javascript-libzim (own release and oz nightly)
        - name: openzim-nightly-volume
          mountPath: "/jails/javascript-libzim/data/openzim/nightly"
          readOnly: false
        - name: openzim-release-volume
          subPath: "javascript-libzim"
          mountPath: "/jails/javascript-libzim/data/openzim/release/javascript-libzim"
          readOnly: false

        # user: kiwix-apple (nightly and own releases)
        - name: kiwix-nightly-volume
          mountPath: "/jails/kiwix-apple/data/kiwix/nightly"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "kiwix-macos"
          mountPath: "/jails/kiwix-apple/data/kiwix/release/kiwix-macos"
          readOnly: false

        # user: kiwix-build (nightly and built projects)
        - name: kiwix-nightly-volume
          mountPath: "/jails/kiwix-build/data/kiwix/nightly"
          readOnly: false
        - name: openzim-nightly-volume
          mountPath: "/jails/kiwix-build/data/openzim/nightly"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "kiwix-desktop"
          mountPath: "/jails/kiwix-build/data/kiwix/release/kiwix-desktop"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "kiwix-tools"
          mountPath: "/jails/kiwix-build/data/kiwix/release/kiwix-tools"
          readOnly: false
        - name: kiwix-release-volume
          subPath: "libkiwix"
          mountPath: "/jails/kiwix-build/data/kiwix/release/libkiwix"
          readOnly: false
        - name: openzim-release-volume
          subPath: "libzim"
          mountPath: "/jails/kiwix-build/data/openzim/release/libzim"
          readOnly: false
        - name: openzim-release-volume
          subPath: "zim-tools"
          mountPath: "/jails/kiwix-build/data/openzim/release/zim-tools"
          readOnly: false
        - name: openzim-release-volume
          subPath: "zimwriterfs"
          mountPath: "/jails/kiwix-build/data/openzim/release/zimwriterfs"
          readOnly: false

        # keys
        - name: host-keys
          subPath: ecdsa
          mountPath: "/etc/ssh/ssh_host_ecdsa_key"
          readOnly: true
        - name: host-pubkeys
          subPath: ecdsa
          mountPath: "/etc/ssh/ssh_host_ecdsa_key.pub"
          readOnly: true
        - name: host-keys
          subPath: ed25519
          mountPath: "/etc/ssh/ssh_host_ed25519_key"
          readOnly: true
        - name: host-pubkeys
          subPath: ed25519
          mountPath: "/etc/ssh/ssh_host_ed25519_key.pub"
          readOnly: true
        - name: host-keys
          subPath: rsa
          mountPath: "/etc/ssh/ssh_host_rsa_key"
          readOnly: true
        - name: host-pubkeys
          subPath: rsa
          mountPath: "/etc/ssh/ssh_host_rsa_key.pub"
          readOnly: true
        ports:
          - containerPort: 22
        resources:
          requests:
            memory: "20Mi"
            cpu: "200m"
      volumes:
      - name: kiwix-release-volume
        persistentVolumeClaim:
          claimName: master-kiwix-release-pvc
      - name: kiwix-nightly-volume
        persistentVolumeClaim:
          claimName: master-kiwix-nightly-pvc
      - name: openzim-release-volume
        persistentVolumeClaim:
          claimName: master-openzim-release-pvc
      - name: openzim-nightly-volume
        persistentVolumeClaim:
          claimName: master-openzim-nightly-pvc
      - name: host-keys
        secret:
          secretName: dropbox-host-keys
          defaultMode: 0600
      - name: host-pubkeys
        configMap:
          name: dropbox-host-pubkeys
          defaultMode: 0644
      nodeSelector:
        k8s.kiwix.org/role: "master"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zim
  name: builds-dropbox-service
  labels:
    app: builds-dropbox-app
spec:
  type: NodePort
  selector:
    app: builds-dropbox-app
  ports:
  - protocol: TCP
    port: 30322
    targetPort: 22
    nodePort: 30322
