apiVersion: batch/v1
kind: CronJob
metadata:
  name: mb-update-hashes
  namespace: zim
spec:
  schedule: "10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - image: ghcr.io/kiwix/mirrorbrain:bookworm
              imagePullPolicy: IfNotPresent
              name: mirrorbrain
              command: ["mb", "makehashes", "/var/www/download.kiwix.org/", "-t", "/usr/share/mirrorbrain"]
              volumeMounts:
              - mountPath: "/var/www/download.kiwix.org"
                name: download-volume
                readOnly: true
              - name: mb-volume
                subPath: hash
                mountPath: "/usr/share/mirrorbrain"
                readOnly: false
              - name: configs
                subPath: mirrorbrain.conf
                mountPath: "/etc/mirrorbrain.conf"
                readOnly: true
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "1000m"
          volumes:
          - name: download-volume
            persistentVolumeClaim:
              claimName: kiwix-download-pvc
          - name: mb-volume
            persistentVolumeClaim:
              claimName: mirrorbrain-support-pvc
          - name: configs
            configMap:
              name: mb-configs
          restartPolicy: Never
          nodeSelector:
            k8s.kiwix.org/role: "storage"
