apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configs
  namespace: mirrors-qa
data:
  SCHEDULER_SLEEP_DURATION: "1m"
  IDLE_WORKER_DURATION: "15m"
  EXPIRE_TEST_DURATION: "1d"
  MAX_PAGE_SIZE: "10"
  # comma-separated
  MIRRORS_EXCLUSION_LIST: "mirror.isoc.org.il"
  init-extensions.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    EOSQL

