apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-mirrors-kiwix-org
  namespace: mirrors-qa
spec:
  secretName: api-mirrors-qa-kiwix-org-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: api.mirrors-qa.kiwix.org
  dnsNames:
  - api.mirrors-qa.kiwix.org
