apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zimfarm
  labels:
    app: ui-app
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - image: ghcr.io/openzim/zimfarm-ui:latest
        imagePullPolicy: Always
        name: ui
        volumeMounts:
        - name: configs
          subPath: config.json
          mountPath: "/usr/share/nginx/html/config.json"
          readOnly: true
        env:
          - name: ENVIRON_PATH
            value: "/usr/share/nginx/html/config_old.json"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "15Mi"
            cpu: "1m"
      volumes:
      - name: configs
        configMap:
          name: ui-configs
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: zimfarm
  name: ui-service
  labels:
    app: ui-app
spec:
  selector:
    app: ui-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
  namespace: zimfarm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - farm.openzim.org
      secretName: farm-openzim-org-tls
  rules:
  - host: farm.openzim.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui-service
            port:
              number: 80
