apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cms
  labels:
    app: api-app
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - image: ghcr.io/openzim/cms-api:latest
        imagePullPolicy: Always
        name: api
        envFrom:
        - configMapRef:
            name: api-configs
        - secretRef:
            name: api-secrets
        volumeMounts:
        - mountPath: "/secrets"
          name: secrets
          readOnly: true
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
      volumes:
      - name: secrets
        secret:
          secretName: api-secrets
          defaultMode: 0600
          optional: false
          items:
          - key: PRIVATE_KEY_CONTENT
            path: id_rsa
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: cms
  name: api-service
  labels:
    app: api-app
spec:
  selector:
    app: api-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: cms
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - api.cms.openzim.org
      secretName: api-cms-openzim-org-tls
  rules:
  - host: api.cms.openzim.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
