apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: services-bt-tracker-pvc
  namespace: bittorrent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: srv-services-bittorrent-bt-tracker-local-pv
