apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nautilus
  labels:
    app: api-app
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - image: ghcr.io/openzim/nautilus-webui-api:latest
        imagePullPolicy: Always
        name: api
        envFrom:
        - configMapRef:
            name: api-configs
        - secretRef:
            name: api-secrets
        volumeMounts:
        - name: files-volume
          mountPath: "/tmp/transient"
          readOnly: false
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
      volumes:
      # /!\ this is not backed-up (considered transient)
      - name: files-volume
        persistentVolumeClaim:
          claimName: nautilus-api-files-pvc
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: nautilus
  name: api-service
  labels:
    app: api-app
spec:
  selector:
    app: api-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: nautilus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "525m"
spec:
  tls:
    - hosts:
      - api.nautilus.openzim.org
      secretName: api-nautilus-openzim-org-tls
  rules:
  - host: api.nautilus.openzim.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
