apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: login
  labels:
    app: token-webhook-prod-app
  name: token-webhook-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-webhook-prod-app
  template:
    metadata:
      labels:
        app: token-webhook-prod-app
    spec:
      containers:
        - name: fastapi-dev
          image: ghcr.io/kiwix/login-token-webhook:latest
          envFrom:
          - configMapRef:
              name: token-webhook-prod-configs
          - secretRef:
              name: token-webhook-prod-secrets
          ports:
            - containerPort: 80
          workingDir: /app
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: login
  name: token-webhook-prod-service
  labels:
    app: token-webhook-prod-app
spec:
  selector:
    app: token-webhook-prod-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: token-webhook-prod-ingress
  namespace: login
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - token-webhook.login.kiwix.org
      secretName: token-webhook-login-kiwix-org-tls
  rules:
  - host: token-webhook.login.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: token-webhook-prod-service
            port:
              number: 80
