apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: browser-zim-hashes-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-storage
  volumeName: srv-b-zim-hashes-local-pv
