apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: browser-wp1-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
  volumeName: srv-b-wp1-local-pv
