apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: browser-download-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: local-storage
  volumeName: srv-b-download-local-pv
