apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: browser-maps-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
  volumeName: srv-b-www-maps-local-pv
