apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dlsvc-geoip-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: local-storage
  volumeName: srv-s-geoip-local-pv
