apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dlsvc-mirrorbrain-db-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100G
  storageClassName: local-storage
  volumeName: srv-s-mirrorbrain-db-local-pv
