apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-kiwix-release-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100G
  storageClassName: local-storage
  volumeName: srv-m-kiwix-release-local-pv
