apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-www-logs-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: local-storage
  volumeName: srv-m-www-logs-local-pv
