apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seeder-files-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Ti
  storageClassName: local-storage
  volumeName: kathrin-seeder-files-local-pv
