apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: services-dev-drive-pvc
  namespace: zim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: srv-services-zim-dev-drive-local-pv
