apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cyon-kiwixorg-pvc
  namespace: website
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: cyon-kiwixorg-pv
