apiVersion: v1
kind: PersistentVolume
metadata:
  name: cyon-kiwixorg-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/cyon-kiwixorg
  claimRef:
    name: cyon-kiwixorg-pvc
    namespace: website
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.kiwix.org/role
              operator: In
              values:
              - services
