apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-ingress
  namespace: website
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/server-snippet: |
      set $shouldRedirect 1;
      if ($uri ~* "/.well-known/acme-challenge/(.+)") {
        set $shouldRedirect 0;
      }

      if ( $shouldRedirect = 1 ) {
        rewrite (?i)^/qr/H1/([A-Z0-9]*)$ "https://get.kiwix.org/en/hotspot-support/?sn=$1" permanent;
        return 301 "https://donate.kiwix.org";
      }
spec:
  tls:
    - hosts:
      - support.kiwix.org
      secretName: support-kiwix-org-tls
  rules:
  - host: support.kiwix.org
    http:

