apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cms
  labels:
    app: ui-app
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - image: ghcr.io/openzim/cms-ui:latest
        imagePullPolicy: Always
        name: ui
        envFrom:
        - configMapRef:
            name: ui-configs
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "16Mi"
            cpu: "1m"
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: cms
  name: ui-service
  labels:
    app: ui-app
spec:
  selector:
    app: ui-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
  namespace: cms
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - cms.openzim.org
      secretName: cms-openzim-org-tls
  rules:
  - host: cms.openzim.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui-service
            port:
              number: 80
