apiVersion: v1
kind: ConfigMap
metadata:
  name: php-configs
  namespace: stats
data:
  www-pool.conf: |
    [www]
    pm.max_children = 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stats
  labels:
    app: matomo-app
  name: matomo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo-app
  template:
    metadata:
      labels:
        app: matomo-app
    spec:
      containers:
      - image: ghcr.io/kiwix/matomo:5.5.0-fpm
        imagePullPolicy: IfNotPresent
        name: matomo
        env:
          # URL to internal web service for cron upload
          - name: MATOMO_URL
            value: "http://matomo-web-service"
          - name: PHP_MEMORY_LIMIT
            value: "3096M"
        volumeMounts:
        - name: files-volume
          mountPath: "/var/www/html/misc/user"
          subPath: branding
          readOnly: false
        - name: files-volume
          mountPath: "/var/www/html"
          subPath: webroot
          readOnly: false
        - name: files-volume
          mountPath: "/var/www/html/config/config.ini.php"
          subPath: config.ini.php
          readOnly: false
        - name: php-configs
          mountPath: "/usr/local/etc/php-fpm.d/zz-www-pool.conf"
          subPath: www-pool.conf
          readOnly: true
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "128Mi"
            cpu: "400m"
      volumes:
      - name: files-volume
        persistentVolumeClaim:
          claimName: matomo-files-pvc
      - name: php-configs
        configMap:
          name: php-configs
      nodeSelector:
        k8s.kiwix.org/role: "stats"
---
apiVersion: v1
kind: Service
metadata:
  namespace: stats
  name: matomo-app-service
  labels:
    app: matomo-app
spec:
  selector:
    app: matomo-app
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
