apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configs
  namespace: stats
data:
  timeout.cnf: |
    [mysqld]
    net_read_timeout    = 43200
    net_write_timeout   = 43200
  pool.cnf: |
    [mysqld]
    skip_name_resolve
    max_allowed_packet=512M
    secure-file-priv = ""
    local-infile=1

    innodb_log_file_size=512M
    innodb_buffer_pool_size=8G
    innodb-buffer-pool-chunk-size=134217728
    innodb_buffer_pool_instances=8

    innodb_flush_log_at_trx_commit=2
    innodb_lru_scan_depth=256
    innodb_page_cleaners=8
    innodb_io_capacity=100

    [mysql]
    local-infile=1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: stats
  labels:
    app: matomo-db
  name: matomo-db-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo-db
  serviceName: matomo-db-service
  template:
    metadata:
      labels:
        app: matomo-db
    spec:
      containers:
      - image: docker.io/mysql:8-debian
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        volumeMounts:
        - name: data-volume
          mountPath: "/var/lib/mysql"
          readOnly: false
        - name: mysql-configs
          mountPath: "/etc/mysql/conf.d"
          readOnly: true
        - mountPath: /tmp
          name: tmpfs
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "10Gi"
            cpu: "3000m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: stats-db-pvc
      - name: mysql-configs
        configMap:
          name: mysql-configs
      - name: tmpfs
        emptyDir:
          medium: Memory
      nodeSelector:
        k8s.kiwix.org/role: "stats"
---
apiVersion: v1
kind: Service
metadata:
  namespace: stats
  name: matomo-db-service
  labels:
    app: matomo-db
spec:
  selector:
    app: matomo-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
