apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cardshop
  labels:
    app: api-app
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - image: ghcr.io/offspot/cardshop-scheduler:latest
        imagePullPolicy: Always
        name: api
        envFrom:
        - configMapRef:
            name: api-configs
        - secretRef:
            name: api-secrets
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "150m"
      nodeSelector:
        k8s.kiwix.org/role: "services"
---
apiVersion: v1
kind: Service
metadata:
  namespace: cardshop
  name: api-service
  labels:
    app: api-app
spec:
  selector:
    app: api-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: cardshop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  tls:
    - hosts:
      - api.imager.kiwix.org
      secretName: api-imager-kiwix-org-tls
  rules:
  - host: api.imager.kiwix.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress-protected
  namespace: cardshop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /shop/stripe/shipment
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: api-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Kiwix Assembly Team only"
spec:
  tls:
    - hosts:
      - api.imager.kiwix.org
      secretName: api-imager-kiwix-org-tls
  rules:
  - host: api.imager.kiwix.org
    http:
      paths:
      - path: /shop/stripe/shipment
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
