name: Library Check

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - main

jobs:

  library:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64
      - name: Install dependencies
        run: pip install -r test-suite/requirements.txt
      - name: Test library.kiwix.org
        working-directory: test-suite
        run: pytest -vvv

  dev-library:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64
      - name: Install dependencies
        run: pip install -r test-suite/requirements.txt
      - name: Test dev.library.kiwix.org
        working-directory: test-suite
        env:
          SCHEMES: http,https
          LIBRARY_HOST: dev.library.kiwix.org
          TIMEOUT: 30
        run: pytest -vvv -m "not varnish"
