name: Mirrors Check

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - main

jobs:

  mirrors:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
      - name: Setup venv
        run: python3 -m venv .venv
      - name: Install dependencies
        run: .venv/bin/pip install -r test-suite/requirements.txt
      - name: Test mirrors
        working-directory: test-suite
        run: ../.venv/bin/python -m pytest -vvv test_mirrors.py
