name: Quarterly Google Play

on:
  schedule:
    - cron: "0 8 * */3 1"

jobs:
  job:
    runs-on: ubuntu-24.04
    steps:
    - name: Create routine issue
      shell: python
      run: |
        import datetime
        import math
        import os
        import re
        import sys

        import requests

        quarter = math.ceil(datetime.date.today().month/3.)

        payload = {
            "title": f"Q{quarter} Google Play Update",
            "body": os.getenv("ISSUE_BODY"),
            "labels": re.sub(r"\s", "", os.getenv("LABELS", "")).split(",") or None,
            "assignees": re.sub(r"\s", "", os.getenv("ASSIGNEES", "")).split(",") or None,
        }
        api_url = f"https://api.github.com/repos/{os.getenv('REPO')}/issues"
        url = f"https://github.com/{os.getenv('REPO')}/issues"
        headers = {
            "Accept": "application/vnd.github.v3+json",
            "Authorization": f"token {os.getenv('ACCESS_TOKEN')}",
        }
        resp = requests.get(api_url, headers=headers)
        if resp.status_code != 200:
            print(f"❌ Couldn't retrieve issues for {url} using {api_url}.")
            print(f"HTTP {resp.status_code} {resp.reason} - {resp.text}")
            print("Check your `ACCESS_TOKEN` secret.")
            sys.exit(1)
        resp = requests.post(api_url, headers=headers, json=payload)
        if resp.status_code != 201:
            print(f"❌ Couldn't create issue for {url}")
            print(f"HTTP {resp.status_code} {resp.reason} - {resp.text}")
            sys.exit(1)
        print(f"✅ Issue successfully created at {url}/{resp.json().get('number')}")
        sys.exit(0)
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPO: kiwix/kiwix-android
        LABELS: store
        ASSIGNEES: kelson42,MohitMaliDeveloper
        ISSUE_BODY: |

          Check that the [Kiwix Team profile](https://play.google.com/store/apps/dev?id=9116215767541857492) and [Kiwix App](https://play.google.com/store/apps/details?id=org.kiwix.kiwixmobile) are up-to-date.

          - [ ] Icons and cover picture
          - [ ] Metadata (title, description)
          - [ ] Screenshots

          [Google Play Console](https://play.google.com/console/u/0/developers/9116215767541857492/app-list)

          **Note**: this is an *automatic reminder* intended for the assignee(s).

