apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zim
  labels:
    app: master-ftpd-app
  name: master-ftpd-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: master-ftpd-app
  template:
    metadata:
      labels:
        app: master-ftpd-app
    spec:
      containers:
      - image: ghcr.io/kiwix/ftpd:latest
        imagePullPolicy: IfNotPresent
        name: pureftpd
        command: ["/usr/sbin/pure-ftpd", "-4", "-H", "-p", "2000:2050", "-S", "0.0.0.0,21", "-P", "srv-m.k8s.kiwix.org"] # "master.download.kiwix.org"]
        volumeMounts:
        - mountPath: "/var/lib/ftp/zim"
          name: zim-volume
          readOnly: true
        - mountPath: "/var/lib/ftp/kiwix/release"
          name: kiwix-release-volume
          readOnly: true
        - mountPath: "/var/lib/ftp/kiwix/nightly"
          name: kiwix-nightly-volume
          readOnly: true
        - mountPath: "/var/lib/ftp/openzim/release"
          name: openzim-release-volume
          readOnly: true
        - mountPath: "/var/lib/ftp/openzim/nightly"
          name: openzim-nightly-volume
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
        ports:
          # using hostPort is reliable with any FTP client for passive mode
          # using nodePort on all but :21 (hostPort) works with some but not all clients
          # alternative would be for those client to use a different port…
        - containerPort: 21
          hostPort: 21
        # k8s doesn't support ranges
        # purposely not using ports above 30000 as those are k8s-reserved (nodePort)
        - containerPort: 2000
          hostPort: 2000
        - containerPort: 2001
          hostPort: 2001
        - containerPort: 2002
          hostPort: 2002
        - containerPort: 2003
          hostPort: 2003
        - containerPort: 2004
          hostPort: 2004
        - containerPort: 2005
          hostPort: 2005
        - containerPort: 2006
          hostPort: 2006
        - containerPort: 2007
          hostPort: 2007
        - containerPort: 2008
          hostPort: 2008
        - containerPort: 2009
          hostPort: 2009
        - containerPort: 2010
          hostPort: 2010
        - containerPort: 2011
          hostPort: 2011
        - containerPort: 2012
          hostPort: 2012
        - containerPort: 2013
          hostPort: 2013
        - containerPort: 2014
          hostPort: 2014
        - containerPort: 2015
          hostPort: 2015
        - containerPort: 2016
          hostPort: 2016
        - containerPort: 2017
          hostPort: 2017
        - containerPort: 2018
          hostPort: 2018
        - containerPort: 2019
          hostPort: 2019
        - containerPort: 2020
          hostPort: 2020
        - containerPort: 2021
          hostPort: 2021
        - containerPort: 2022
          hostPort: 2022
        - containerPort: 2023
          hostPort: 2023
        - containerPort: 2024
          hostPort: 2024
        - containerPort: 2025
          hostPort: 2025
        - containerPort: 2026
          hostPort: 2026
        - containerPort: 2027
          hostPort: 2027
        - containerPort: 2028
          hostPort: 2028
        - containerPort: 2029
          hostPort: 2029
        - containerPort: 2030
          hostPort: 2030
        - containerPort: 2031
          hostPort: 2031
        - containerPort: 2032
          hostPort: 2032
        - containerPort: 2033
          hostPort: 2033
        - containerPort: 2034
          hostPort: 2034
        - containerPort: 2035
          hostPort: 2035
        - containerPort: 2036
          hostPort: 2036
        - containerPort: 2037
          hostPort: 2037
        - containerPort: 2038
          hostPort: 2038
        - containerPort: 2039
          hostPort: 2039
        - containerPort: 2040
          hostPort: 2040
        - containerPort: 2041
          hostPort: 2041
        - containerPort: 2042
          hostPort: 2042
        - containerPort: 2043
          hostPort: 2043
        - containerPort: 2044
          hostPort: 2044
        - containerPort: 2045
          hostPort: 2045
        - containerPort: 2046
          hostPort: 2046
        - containerPort: 2047
          hostPort: 2047
        - containerPort: 2048
          hostPort: 2048
        - containerPort: 2049
          hostPort: 2049
        - containerPort: 2050
          hostPort: 2050
      volumes:
      - name: zim-volume
        persistentVolumeClaim:
          claimName: master-zim-pvc
      - name: kiwix-release-volume
        persistentVolumeClaim:
          claimName: master-kiwix-release-pvc
      - name: kiwix-nightly-volume
        persistentVolumeClaim:
          claimName: master-kiwix-nightly-pvc
      - name: openzim-release-volume
        persistentVolumeClaim:
          claimName: master-openzim-release-pvc
      - name: openzim-nightly-volume
        persistentVolumeClaim:
          claimName: master-openzim-nightly-pvc
      nodeSelector:
        k8s.kiwix.org/role: "master"
